### PR TITLE
Make Directory.defaultSortComparator public

### PR DESCRIPTION
**Pull request by LoganDark**
I want to use this in my own comparator :(

### CODE REVIEW

**Comment by NeekSandhu** [comment]
I'll let you know here when I make the minor release later tonight

**Comment by zikaari** [comment]
Available now in `aspen-core@1.0.5`. Since it's just a patch version bump, you can upgrade to the latest version of just this package without having to upgrade all dependents. The dependents won't wont mind since they are all `^1.0.4`, thus they will accept, `^1.0.5` just fine. _Manually verify that you don't have duplicate installs though._

**Comment by LoganDark** [comment]
Indeed, that's how patches work :)

**Comment by zikaari** [comment]
Very true. But wanted to let you know that the dependents use `aspen-core` as `^1.0.4` instead of a strict `1.0.4`. In which case we'd have to update the entire dependent graph.

Also, I haven't had a very smooth experience while [trying to upgrade indirect dependencies](https://github.com/yarnpkg/yarn/issues/4986), at least when using Yarn.

**Comment by LoganDark** [comment]
> Very true. But wanted to let you know that the dependents use `aspen-core` as `^1.0.4` instead of a strict `1.0.4`. In which case we'd have to update the entire dependent graph.

Would be weird if they did the latter. `^1.0.4` is the default.

> Also, I haven't had a very smooth experience while [trying to upgrade indirect dependencies](https://github.com/yarnpkg/yarn/issues/4986), at least when using Yarn.

Luckily I don't use yarn, I use normal npm. It has [some bugs](https://github.com/npm/cli/issues/3629), but the official solution in this case is a lot better than the alternative.

**Pull request merged**
